### ISSUE TITLE
[barcodes_generator] Limited barcode sequence

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-barcode#105]
Companies usually purchase a limited number of segment of UPC's.  Would be interesting to pre-allocate the segment into the rule, and ensure that the user gets a proper error message when all UPC's have been allocated.

Perhaps this would require adding a 'Max Number' field in `ir.sequence`, and triggering an error message when the max is going to be exceeded.

**Comment by rousseldenis** [comment]
@jbeficent What's the status of this ? Does it need a RFC ?
