### ISSUE TITLE
installing module Generate Barcodes for Stock Production Lots

### ISSUE THREAD

**Issue by Hamza-Talibi** [OCA/stock-logistics-barcode#107]
Hi @lasley 
When I try to install the module Generate Barcodes for Stock Production Lots I get an error in this line
https://github.com/OCA/stock-logistics-barcode/blob/15f23e157032e9739b1fe60eb85fe74b458a7391/barcodes_generator_abstract/models/barcode_generate_mixin.py#L70

The traceback:

File "/home/odoo10/odoo-dev/odoo/extra-addons/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 70, in generate_barcode
    barcode_class = item.get_barcode_class(
ParseError: "'stock.production.lot' object has no attribute 'get_barcode_class'" while parsing /home/odoo10/odoo-dev/odoo/extra-addons/barcodes_generator_lot/demo/function.xml:15, near
<function model="stock.production.lot" name="generate_barcode" eval="[ref('stock_production_lot_barcode')]"/>

Thank you

**Comment by lasley** [comment]
@Hamza-Talibi - You can replicate this on Runbot?

That line is supposed to be interacting with the `barcode` Python library, not a lot record. Additionally, your traceback shows a different line than the one that actually exists in this repo:

This repo:
```
 barcode_class = barcode.get_barcode_class( 
```

Your traceback:
```
barcode_class = item.get_barcode_class(
```

[`item.get_barcode_class` does not exist in this repo](https://github.com/OCA/stock-logistics-barcode/search?utf8=%E2%9C%93&q=%22item.get_barcode_class%22&type=)

**Comment by lasley** [comment]
My guess is you need to install [`viivakoodi`](https://github.com/OCA/stock-logistics-barcode/blob/10.0/requirements.txt#L2)

**Comment by MeetKD** [comment]
@Hamza-Talibi @lasley I have installed this Viivakoodi lib but I am still facing the same error. Any help ?
