### ISSUE TITLE
10.0 barcodes_generator_product

### ISSUE THREAD

**Issue by tomwic** [OCA/stock-logistics-barcode#113]
barcode rule is not visible on product cart/template even done correctly in Barcode Nomenclatures section.

**Comment by legalsylvain** [comment]
does your user belong to the correct group ? 

https://github.com/OCA/stock-logistics-barcode/blob/10.0/barcodes_generator_product/views/view_product_product.xml#L18

regards.

**Comment by rousseldenis** [comment]
@tomwic Any news on this issue ?

**Comment by rousseldenis** [comment]
@tomwic
