### ISSUE TITLE
Odoo server can't start when stock_scanner is installed with queue_job.

### ISSUE THREAD

**Issue by benwillig** [OCA/stock-logistics-barcode#126]
There is a problem when ```stock_scanner``` module is installed among ```queue_job``` module. [This line](https://github.com/OCA/queue/blob/10.0/queue_job/models/base.py#L20) inspects the model and tries to get the value of each property of the class. Because of the new methods, a singleton error is raised when the server is starting.

I don't know if ```queue_job``` module should be fixed rather than ```stock_scanner```.(https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L2445).

As @sylvain-garancher said in https://github.com/OCA/stock-logistics-barcode/pull/117, there is a problem with compute and inverse methods.

In my opinion, we should add new ```Serialized``` fields instead of trying to work with ```Char``` fields.

**Comment by rousseldenis** [comment]
Closing this as fixed
