### ISSUE TITLE
Cannot install barcodes_generator_abstract in Odoo 10.0 - "No module named barcode" message

### ISSUE THREAD

**Issue by fhrancis** [OCA/stock-logistics-barcode#161]
The viivakoodi library is already installed.
Tryed to install from Aplications within Odoo 10 and received the message "No module named barcode".
Tryed to install with:  pip install odoo10_addon_barcodes_generator_abstract 
And this is the message:
-------------------------------------------------------------------------------------
Collecting odoo10_addon_barcodes_generator_abstract
  Downloading https://files.pythonhosted.org/packages/c4/c4/a3ad241476e9826d527487ccfe89cde891ad9cf07ed43d46d22a93f8e0eb/odoo10_addon_barcodes_generator_abstract-10.0.1.0.3-py2-none-any.whl (129kB)
    100% |████████████████████████████████| 133kB 497kB/s 
Requirement already satisfied: viivakoodi in /usr/local/lib/python2.7/dist-packages (from odoo10_addon_barcodes_generator_abstract) (0.8.0)
Collecting odoo<10.1dev,>=10.0 (from odoo10_addon_barcodes_generator_abstract)
  Could not find a version that satisfies the requirement odoo<10.1dev,>=10.0 (from odoo10_addon_barcodes_generator_abstract) (from versions: )
No matching distribution found for odoo<10.1dev,>=10.0 (from odoo10_addon_barcodes_generator_abstract)
-----------------------------------------------------------------------------------------

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo-community.org), so please be sure you are installing the library in the proper environment.
