### ISSUE TITLE
[11.0][Multi Ean]Support different barcodes format

### ISSUE THREAD

**Issue by infoitservit** [OCA/stock-logistics-barcode#166]
A big part of the products we manage are referenced by multiple barcodes (same product, many barcodes during the years) and with barcodes like UPC-A or, in some case, other strange formats.
Is it possibile to adapt the product_multi_ean module to accept different types of barcodes? Could be enough (or safe) to remove the ean13 validation within the ProductEan13 class?
I tried to find other modules to store multi barcodes for the same product, but i didn't find anything else better than this one.

Thanks

**Comment by infoitservit** [comment]
No way? Should I close this improvement post?

**Comment by rousseldenis** [comment]
Hi @infoitservit,

I think this is a common asking in advanced product management.
Indeed, I think the product_multi_ean module should be improved to support all barcode formats and not only ean13 (but maybe field name is wrong and this can be used to manage multi barcode types).

Maybe @guewen @gurneyalex @pedrobaeza @xavierjimenez who worked on that module could help.

**Comment by pedrobaeza** [comment]
Yes, it's interesting, but no customer is financing this improvement right now, so we are not going to develop it for free.

**Comment by infoitservit** [comment]
Ok @pedrobaeza, let me understand how it goes. The odoo community could or not ask improvements to the odoo company? Should we expect free updates or should we rely on the odoo developer's community and partner to get some improvement like this?

No critics, just to understand how I should act next time.

**Comment by pedrobaeza** [comment]
It's totally legit to suggest improvements. Sometimes the developer hasn't thought on that.

But that improvements might or not be developed ever, depending on the will/needs of the contributors. If you are not able to develop them, maybe you can finance that contributor to do it and make sure it gets OCA.
