### ISSUE TITLE
[11.0] AttributeError: module 'odoo.fields' has no attribute 'Serialized'

### ISSUE THREAD

**Issue by mrddter** [OCA/stock-logistics-barcode#177]
I catch this error after last update, may you help me?

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
>     execute(self.server.app)
>   File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
>     application_iter = app(environ, start_response)
>   File "/opt/odoo/odoo/odoo/service/server.py", line 250, in app
>     return self.app(e, s)
>   File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 166, in application
>     return application_unproxied(environ, start_response)
>   File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
>     result = handler(environ, start_response)
>   File "/opt/odoo/odoo/odoo/http.py", line 1317, in __call__
>     self.load_addons()
>   File "/opt/odoo/odoo/odoo/http.py", line 1349, in load_addons
>     m = __import__('odoo.addons.' + module)
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
> 
>   File "/opt/odoo/odoo/odoo/modules/module.py", line 82, in load_module
>     exec(open(modfile, 'rb').read(), new_mod.__dict__)
>   File "<string>", line 6, in <module>
> 
>   File "/opt/odoo/community_addons/bundles/stock-logistics-barcode/stock_scanner/models/__init__.py", line 8, in <module>
>     from . import scanner_hardware
>   File "/opt/odoo/community_addons/bundles/stock-logistics-barcode/stock_scanner/models/scanner_hardware.py", line 37, in <module>
>     class ScannerHardware(models.Model):
>   File "/opt/odoo/community_addons/bundles/stock-logistics-barcode/stock_scanner/models/scanner_hardware.py", line 152, in ScannerHardware
>     tmp_values = fields.Serialized(
> AttributeError: module 'odoo.fields' has no attribute 'Serialized'

**Comment by pedrobaeza** [comment]
You need to have `base_sparse_field` module installed and the service restarted.

**Comment by hugho-ad** [comment]
@pedrobaeza 

Why base_sparse_field need to be installed? at my odoo instance, stock_scanner module is not installed, I don't get it

**Comment by pedrobaeza** [comment]
Well, this module uses it, and due to Python way of acting, you need it, or leave that module outside addons_path.
