### ISSUE TITLE
Replace stock_picking_barcode thats was existing in odoo 8

### ISSUE THREAD

**Issue by agent-z28** [OCA/stock-logistics-barcode#181]
In v8 was the Barcode Scanner implemented in core as Controller.
in v9 it was removed.
IT Projects LLC migrated it to v11/12 
https://github.com/it-projects-llc/website-addons/tree/12.0/stock_picking_barcode

The design was bad, even in v8.

E.G. Loading the view, it loads all LOCATIONS, in our case thousands.

Is anyone already on the topic, to generate a new, state of the art, mobile based barcode scanner?

**Comment by pedrobaeza** [comment]
AFAIK, the barcode listener is now integrated in the core and activated in current picking form view.

**Comment by agent-z28** [comment]
AFAIK the whole module has been removed. its has been replaced by enterprise modules.
We should quickly replace it.
I'm just asking bcs we dont wanna develop again everything new, and then somebody else did already the same PR:)

**Comment by pedrobaeza** [comment]
Indeed the module is removed, but barcode is integrated now in main module.

**Comment by agent-z28** [comment]
I dont know what the idea of controller in the stock is, 
but its for sure not a stock_picking_controller?!
At the moment in v11 v12 theres no way to have a picking being done in the warehouse!

**Comment by pedrobaeza** [comment]
I think the second section is in community: https://www.odoo.com/documentation/user/11.0/inventory/barcode/operations/delivery.html
