### ISSUE TITLE
We have a module to add a barcode to every location. Also the labels can be directly printed

### ISSUE THREAD

**Issue by agent-z28** [OCA/stock-logistics-barcode#182]
Is anyone interested? 
If yes, is this the right repos fot the PR=?

**Comment by pedrobaeza** [comment]
Isn't this https://github.com/OCA/stock-logistics-barcode/tree/10.0/barcodes_generator_location?

**Comment by agent-z28** [comment]
Yes looks like the same :( We double implemented :///
