### ISSUE TITLE
Wrong expr path in res.config.setting

### ISSUE THREAD

**Issue by kos94ok-3D** [OCA/stock-logistics-barcode#183]
https://github.com/OCA/stock-logistics-barcode/blob/b45987a51a8976413b9df8db3aeb299f8ff513c6/stock_scanner/wizard/res_config_settings.xml#L10

Try to use expr="//div[@data-key='stock']" position="inside"

**Comment by pedrobaeza** [comment]
Why wrong path? Maybe it's only in your use case. Any way, you can do a PR if you consider this can be improved. You are not even saying the Odoo version...

**Comment by kos94ok-3D** [comment]
Odoo11 CE, I do not see this options in my odoo

**Comment by pedrobaeza** [comment]
I still don't see what is the wrong expression...

**Comment by kos94ok-3D** [comment]
![изображение](https://user-images.githubusercontent.com/33932458/60606280-b9a08880-9dc3-11e9-87e5-de188f141fe1.png)
this element is not child for stock

**Comment by pedrobaeza** [comment]
Sorry, but the screenshot is not readable, but any way, what are you trying to say? Prove it with screenshots, please.

**Comment by pedrobaeza** [comment]
And try on the OCA runbot link for showing how it's expected.

**Comment by kos94ok-3D** [comment]
I`m sorry, but I can not do it because this module is not exist here:
http://3376716-11-0-1f1cac.runbot1.odoo-community.org/web?debug=1#view_type=list&model=ir.module.module&action=31

**Comment by pedrobaeza** [comment]
You can find it in http://3372050-11-0-b45987.runbot1.odoo-community.org

**Comment by kos94ok-3D** [comment]
Instance: http://3372050-11-0-b45987.runbot1.odoo-community.org/web?debug=1#id=&view_type=form&model=res.config.settings&menu_id=179&action=278
and screenshot without block 'Configure scanner module'
![изображение](https://user-images.githubusercontent.com/33932458/60607194-7fd08180-9dc5-11e9-9e42-58f873e7e83c.png)

**Comment by pedrobaeza** [comment]
OK, after 4 messages, you are finally saying the problem, that is that the block is not shown... Why haven't you say it from the beginning? @misern2 I think you were the migrator. Can you check?

**Comment by kos94ok-3D** [comment]
It happened in this commit:
https://github.com/OCA/stock-logistics-barcode/commit/dd34bc2195ebe09ef6e5cf0930c5490db1640c51#diff-e094b656d253644c84c8a37e9af7c91f

**Comment by rousseldenis** [comment]
@kos94ok-3D Ok, confirmed on runbot. Do you maybe want to make a PR to fix this ?

**Comment by kos94ok-3D** [comment]
Only create PR without Cla and something else?

**Comment by kos94ok-3D** [comment]
It will be cool. Must I send signed CLA before?

**Comment by pedrobaeza** [comment]
When you want, but before merging the PR
