### ISSUE TITLE
[11.0] Stock scanner: AttributeError: module 'odoo.fields' has no attribute 'Serialized'

### ISSUE THREAD

**Issue by kos94ok-3D** [OCA/stock-logistics-barcode#186]
![изображение](https://user-images.githubusercontent.com/33932458/60828142-614dfa00-a1ba-11e9-9e96-2f1933c2c902.png)
I do not know how get it in runbot.
If I import fields from base_sparse_field module, all is OK.
> from odoo import models, api, exceptions
> from odoo.addons.base_sparse_field.models.fields import fields

Can someone check it on own instance?

**Comment by pedrobaeza** [comment]
You have to put in your config file to load as server wide module `base_sparse_field` module.
