### ISSUE TITLE
[REF] Switching from viivakoodi lib to python-barcode (back)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/stock-logistics-barcode#193]
Ref of this issue : [this comment](https://github.com/OCA/stock-logistics-barcode/pull/119#issuecomment-516057377).

> @yucer said : 
> Is there another project python-barcode that seems to be a fork from viivakoodi. It has additional releases and cleaner packaging.
> Also it has less TODOs. One of them Improve Python 3 support seems to be done. Do you thing it can be used instead of viivakoodi ?

Hi @yucer, 
Python-barcode is not a fork ! viivakoodi is a fork of python-barcode. (ref : https://github.com/OCA/stock-logistics-barcode/pull/76) And we switched because python-barcode was not active anymore. (In fact Bitbucket old links are now broken)
But well, now, python-barcode seems to be more active than viivakoodi.

It seems that @lasley is now maintainer of viivakoodi. [ref](https://github.com/OCA/stock-logistics-barcode/pull/76#issuecomment-275727514). @lasley : what do you think about that proposal ?

I'm personaly fully open to switch from a lib to another.
- I have no tecnical point of view
- regarding community activity, I'm in favor of the switch

**Viivakoodi activity :**

- 7 contributors, 0 commits since 2 years.

![image](https://user-images.githubusercontent.com/3407482/62065868-317d9980-b230-11e9-8cdd-23e43586aa7b.png)

**Python-barcode activity :** 

- 13 contributors, several commits in 2019.

![image](https://user-images.githubusercontent.com/3407482/62065836-23c81400-b230-11e9-8638-f85381bca632.png)

@yucer, do you want to make the PR to switch the lib, to see if all is OK ? 

regards.

**Comment by yucer** [comment]
> @yucer, do you want to make the PR to switch the lib, to see if all is OK ?

Done let us see if there are no regressions. I suppose that the programming interface is the same.

**Comment by yucer** [comment]
However, there is something new: `python-barcode` uses `Pillow` instead of `PIL` when generating raster images.

Does this project generates only vector images (.SVG) ?  

How many things in `Odoo` or `OCA` projects use `PIL` or `Pillow` features?
