### ISSUE TITLE
Difference between these modules and Odoo Enterprise Barcode

### ISSUE THREAD

**Issue by kittiu** [OCA/stock-logistics-barcode#199]
Hi, we are quite new to using barcode scanning, but interested to join, i..e, upgrade to v12 (as I see many are left tbd).
I have some questions to get to know. What is the main difference between here, and Odoo Ent's Barcode https://www.odoo.com/documentation/user/12.0/inventory/barcode.html ?

**Comment by pedrobaeza** [comment]
This is for anything involving barcodes. For example, barcode numbers generators. This is not something in enterprise.

There's also the stock_scanner module which is an independent daemon for doing scans in batch, which for some scenarios are interesting.

And finally, see #195 for an optimized replacement of the enterprise barcode scan module.
