### ISSUE TITLE
odoo12 : Guid to install stock-logistics-barcode

### ISSUE THREAD

**Issue by hassanlaarej** [OCA/stock-logistics-barcode#209]
i try to install odoo12 stock-logistics-barcode by making source in addons or by pip3 but i can't view this modules in the interface.
tanks by advance

**Comment by rousseldenis** [comment]
@hassanlaarej That depends on your configuration. But either you should see the path to the modules in the server log when launching Odoo.

If so, you need to update modules list (in the interface).
