### ISSUE TITLE
Help, how install on windows 10?

### ISSUE THREAD

**Issue by DanLaur** [OCA/stock-logistics-barcode#210]
Hi, I'm new Odoo user, I'm try it on localhost windows 10. I've learn how install external modules, but I can't install this module, don't work.
I've unzip file and put it in addons folder.
I've odoo in developer mode, I've restarted odoo and postgree service, and i've update modules list.
But when I search module, I don't find it!
Anyone can help me?
Thanks

**Comment by rousseldenis** [comment]
Hi @DanLaur. I think this is not the best place for this question.

Maybe there : https://www.odoo.com/fr_FR/forum/
