### ISSUE TITLE
EAN tree does not appear

### ISSUE THREAD

**Issue by manuelcalerosolis** [OCA/stock-logistics-barcode#220]
I have installed the module and in the product form, the control to represent the bar codes does not appear.

You can see how the runboot does not appear, it is more not to appear or within the inherited views.

Regards.

**Comment by pedrobaeza** [comment]
Which module? Which version? Screenshots?

**Comment by manuelcalerosolis** [comment]
Sorry,
module : product_multi_ean
version : odoo 12.0

![image](https://user-images.githubusercontent.com/3088246/67487147-b6305600-f66d-11e9-88b1-a2f3012f5c58.png)

Thanks.

**Comment by bodedra** [comment]
@manuelcalerosolis You can see that fields at Product Variant form not on Product Template. As per your shared screen shot shows Product Template form view.

CC @pedrobaeza

**Comment by pedrobaeza** [comment]
Closing as answered

**Comment by manuelcalerosolis** [comment]
> @manuelcalerosolis You can see that fields at Product Variant form not on Product Template. As per your shared screen shot shows Product Template form view.
> 
> CC @pedrobaeza

Do I have to create variants to be able to assign several barcodes to a product?

A product can have multiple bar codes during its life cycle, without having to have different properties.

Regards.

**Comment by pedrobaeza** [comment]
You have to show product variants, or improve the code of the module for being able to put it in template when there's only one variant.

**Comment by manuelcalerosolis** [comment]
We will study the module code to try not to create variants. 

Thanks Pedro.

**Comment by pedrobaeza** [comment]
But you are in a wrong assumption: variants are always created. Specifically one when there are no attributes, and more if some attributes with values that create variants.

**Comment by bodedra** [comment]
IMO You should give/enable access right "Manage Product Variants" to your Users. Refresh your page, and now you can see new menu with "Product Variants". Search your desire product and assign multiple EAN. That's it.

**Comment by manuelcalerosolis** [comment]
That is exactly what I do.

![image](https://user-images.githubusercontent.com/3088246/67516915-c3ffce80-f6a1-11e9-950f-9c7c86bcb71a.png)

There is no way to enter a new barcode.

![image](https://user-images.githubusercontent.com/3088246/67517102-1e992a80-f6a2-11e9-9018-57a250fbdbc8.png)

**Comment by pedrobaeza** [comment]
And why don't you tell this from the beginning? The module only gives the basic read permission, but extra modules (or manually), you have to add the corresponding extra permissions for creating/deleting/modifying (salesperson for example). Maybe full access can be given to admins in this module, but due to dependencies, no others can be given.

**Comment by manuelcalerosolis** [comment]
How do you want me to know, if I didn't see control before?

**Comment by pedrobaeza** [comment]
Well, looking at the module code you see it clear that is over product.product, not over product.template. Any way, it seems this issue has mutated in its form along the time.

**Comment by manuelcalerosolis** [comment]
Today I learned the difference between product.product and product.template. 
Anyway I think that the README.rst file of the module could help people who for the first time want to use it.

**Comment by legalsylvain** [comment]
@manuelcalerosolis, could you take time to make a PR in this direction, improving readme file ?

**Comment by manuelcalerosolis** [comment]
Of course I will be delighted

**Comment by manuelcalerosolis** [comment]
Working with the module I have discovered that it is not useful to sell a product for any of its barcodes, which does not meet my expectations.
