### ISSUE TITLE
Stock_Scanner 10.0 Can't backup my scanner scenario

### ISSUE THREAD

**Issue by Tim-ess** [OCA/stock-logistics-barcode#233]
I built some scanner scenario’s with your stock scanner module wich works perfect.
Now I want to make a backup of the scenario’s I have written.
With the module comes the python script export_scenario.py.
When I run it it says except Exception, e: Syntax Error.
I tried running the script in the docker container (where i run odoo10) but when i run the script I get the following.
2019-12-04 13:29:08,072 - check_parent_store - INFO - Open connection to "localhost:8070" on "demo" with user "admin"
2019-12-04 13:29:08,072 - check_parent_store - ERROR - Fail to connect to the server
2019-12-04 13:29:08,072 - check_parent_store - ERROR –
I have also tried running it on a seperate machine but that just gives a syntax error.
I looked on the internet as well but couldn’t find an answer.
Could you please give me some help with this problem?

**Comment by pedrobaeza** [comment]
Odoo version? Do you have latest code of the module?

**Comment by Tim-ess** [comment]
I have version 10.0.1.1.1 of the module @pedrobaeza

**Comment by pedrobaeza** [comment]
OK, let's see if some of the maintainers of the module can say anything.

**Comment by Tim-ess** [comment]
yes I will be waiting :)

**Comment by rousseldenis** [comment]
> I built some scanner scenario’s with your stock scanner module wich works perfect.
> Now I want to make a backup of the scenario’s I have written.
> With the module comes the python script export_scenario.py.
> When I run it it says except Exception, e: Syntax Error.
> I tried running the script in the docker container (where i run odoo10) but when i run the script I get the following.
> 2019-12-04 13:29:08,072 - check_parent_store - INFO - Open connection to "localhost:8070" on "demo" with user "admin"
> 2019-12-04 13:29:08,072 - check_parent_store - ERROR - Fail to connect to the server
> 2019-12-04 13:29:08,072 - check_parent_store - ERROR –
> I have also tried running it on a seperate machine but that just gives a syntax error.
> I looked on the internet as well but couldn’t find an answer.
> Could you please give me some help with this problem?

Hi @Tim-ess, when running the export script, your Odoo instance needs to run at the same time.

Moreover, you need to pass arguments for connection. See openobject library GetParser for standard arguments : https://github.com/subteno-it/openobject-library/blob/1.0/oobjlib/common.py#L33

**Comment by Tim-ess** [comment]
Thx or your response. Your solution worked for me along with the right arguments for the scenario's I wanted to export. Thanks a lot!

**Comment by rousseldenis** [comment]
> Thx or your response. Your solution worked for me along with the right arguments for the scenario's I wanted to export. Thanks a lot!

You're welcome!
