### ISSUE TITLE
[v12][stock_barcodes]

### ISSUE THREAD

**Issue by zitom4** [OCA/stock-logistics-barcode#239]
Hello!

My name is Lorenzo, from Sistemas de datos, Tenerife, Canary Islands.

I just opened the following issue:
[https://github.com/odoo/odoo/issues/42835](https://github.com/odoo/odoo/issues/42835)

We found the mentioned error using this module, but i think the problem is in the standard module, because since any module that inherits from it will find the same problem. However, @pedrobaeza told me that I must open the report here.

I hope it helps.

**Comment by pedrobaeza** [comment]
@sergio-teruel is that a problem that you have faced?

**Comment by sergio-teruel** [comment]
I don't know this issue ... mybe are you scanning in manual entry mode??

**Comment by zitom4** [comment]
No, i'm not in manual entry mode.

With an example, you will surely see it better. I don't know if you have tried this before.

If i read the following barcode : 8480000650672.

![IMG_20200107_152946](https://user-images.githubusercontent.com/5501212/71907545-2b3b0400-3164-11ea-94af-8c6108456229.jpg)

This is the result:

![Video](https://user-images.githubusercontent.com/5501212/71907948-01361180-3165-11ea-9a46-153fa8e83119.gif)

As you can see, it divides the barcode in two parts. First insert into the input 8480000, the reading is interrumpted by the on screen keyboard, shown by the focus() event, an then insert the other barcode part : 650672.

I if add the attribute mentioned above, it works as it should.

**Comment by sergio-teruel** [comment]
Ok I see nos!! . I will research it

**Comment by sergio-teruel** [comment]
Can you add a video with all process... I am seeing location field empty.... !!

**Comment by sergio-teruel** [comment]
Ok, I know whats happend... your issue is due to speed scanner transmit data....
You must adjust this and you can try with the Odoo system parameter "barcode.max_time_between_keys_in_ms".
@pedrobaeza you can close this issue.

**Comment by pedrobaeza** [comment]
Thanks for checking, Sergio. Maybe this can be documented in the README of the module for future references?

**Comment by zitom4** [comment]
> Ok, I know whats happend... your issue is due to speed scanner transmit data....
> You must adjust this and you can try with the Odoo system parameter "barcode.max_time_between_keys_in_ms".
> @pedrobaeza you can close this issue.

Yes Sergio. This is what i was talking about in the original post, in this paragraph:
![image](https://user-images.githubusercontent.com/5501212/72052183-913a9f00-32bc-11ea-8133-b92122512066.png)

As you told, a good way to solve it is adding these parameter. For us, with a low range barcode scanner we must adjust it up to 500ms.
If the inputmode attribute were supported by all browsers, i think it would be a better solution, because it would not make the configuration dependent on the device. Chrome have it implemented  since release 66, and is probably that other browsers as firefox will also do it soon.

Thanks to both of you.
