### ISSUE TITLE
Mobile UI (App Picking) Login Form

### ISSUE THREAD

**Issue by sm2x** [OCA/stock-logistics-barcode#242]
On Login Form, Database selector is not clickable therefore you can not select db on mobile/smartphone device.

**Comment by legalsylvain** [comment]
Could you try with another browser. 
See know issue (on other similar module mobile_app_inventory / V8).
https://github.com/OCA/stock-logistics-barcode/tree/8.0/mobile_app_inventory#known-issues

regards.

**Comment by sm2x** [comment]
tried 3 browsers (chrome, firefox, safari), and yet the same results

**Comment by sm2x** [comment]
ping!

**Comment by sm2x** [comment]
ping!
@PSC member, kindly apply the "no stale" label thank you.
