### ISSUE TITLE
barcodes_generator_partner not available on pypi for v12

### ISSUE THREAD

**Issue by eLBati** [OCA/stock-logistics-barcode#246]
https://pypi.org/project/odoo12-addon-barcodes-generator-partner/ page not found

**Comment by eLBati** [comment]
@sbidoul do you know why?
Thanks

**Comment by sbidoul** [comment]
I see nothing obvious and no error in the bot log... strange

**Comment by pedrobaeza** [comment]
I think it has been the problem with the readme. See my comment in the PR

**Comment by sbidoul** [comment]
So it should land on PyPI tomorrow.

**Comment by sbidoul** [comment]
See also discussion in #244 and https://github.com/OCA/maintainer-tools/issues/441 for the root cause.

**Comment by sbidoul** [comment]
@eLBati further digging into this. Actually the real reason it is not on PyPI is that the pypi publishing occurs on a nightly basis. 

But it was not on https://wheelhouse.odoo-community.org/oca-simple/ either. And the reason for that is that #244 was merged without bumping version and in that case the wheel generator does not kick in immediately, it waits for the nightly batch. This touches the issue of generating a round version number in migration commits...

**Comment by eLBati** [comment]
Thanks!
