### ISSUE TITLE
[12.0] No Barcode Generation on variants

### ISSUE THREAD

**Issue by heymanh** [OCA/stock-logistics-barcode#260]
After barcode generation configuration for products, add variants to product, you will see that:
1. On the variants, no button for barcode generation
2. Still a button for generation on initial product, normally, the barcode field disappear when product has variants 

Here is a patch adding variant support 
[0001-Support-for-Variants.patch.zip](https://github.com/OCA/stock-logistics-barcode/files/4342928/0001-Support-for-Variants.patch.zip)

**Comment by legalsylvain** [comment]
Hi @heymanh. Thanks for reporting the bug. Could you make a PR ? 
kind regard.

**Comment by heymanh** [comment]
Hi @legalsylvain,
Thank you for all the work you are sharing with the community.
I've created the PR, https://github.com/OCA/stock-logistics-barcode/pull/261
Kind regards

**Comment by conroyke56** [comment]
Any updates on if the pull will be processed?
We are running into the same issue. 

Thanks,
