### ISSUE TITLE
Missing barcode on stock.report_lot_barcode

### ISSUE THREAD

**Issue by Whytehorse** [OCA/stock-logistics-barcode#27]
Barcodes are missing. Not sure where to begin. I installed reportlab and all the fonts. The serial number shows up fine but the barcode is just a small black box with an outline where the barcode should be. Is there some mroe fonts needed or something? FYI product barcode printing works fine, it's just the lot serial number that has issues.

**Comment by pedrobaeza** [comment]
This is not something related to this project, and also that you don't have to publish as an issue, because this is not a bug. Anyways, this is what I do for having barcodes:

```
wget http://www.reportlab.com/ftp/fonts/pfbfer.zip --directory-prefix=/tmp/
unzip /tmp/pfbfer.zip -d /tmp/pfbfer
sudo mkdir /usr/lib/python2.7/dist-packages/reportlab/fonts
sudo mv /tmp/pfbfer/* /usr/lib/python2.7/dist-packages/reportlab/fonts
sudo chmod +r /usr/lib/python2.7/dist-packages/reportlab/fonts -R
rm /tmp/pfbfer* -R
```

If you don't still have it, you should go to Odoo forums for more support.

**Comment by Whytehorse** [comment]
thank you. Opened the issue in the correct place here:
https://github.com/steedos/odoo8/issues/1
