### ISSUE TITLE
[13.0] stock_barcodes serial tracked products handling

### ISSUE THREAD

**Issue by levkar** [OCA/stock-logistics-barcode#274]
Currently stock_barcodes module is incrementng quantity if a product is tracked by serial. This leads an error on next step since you can have the same serial on one product and its quantity must be 1.0. 

It might give an error message (or  ignore the the serial barcode since it is already assigned).

I can send a PR if we agree on the correct action.

**Comment by poiswe** [comment]
Hi, any progress regarding this issue?

**Comment by sergio-teruel** [comment]
Sorry!! I agree with @levkar ... Do you can make a PR with the improbement??
