### ISSUE TITLE
[13.0] GS1-128 barcodes parsed incorrectly

### ISSUE THREAD

**Issue by ralyqui** [OCA/stock-logistics-barcode#281]
Currently when scanning a qs1-128 barcode with three AI's 01,17,10 GTIN is not parsed correctly.

As far as I can see the decoder is already supported for version 13, is there some additional dependency that I am missing?

**Comment by pedrobaeza** [comment]
What do you expect to happen and with which modules?

**Comment by ralyqui** [comment]
After installing every module from the branch 13 I expect to either go into inventory and be able to scan barcodes there or use the barcode app. Unfortunately, there is no way to scan barcodes from the inventory and the barcode app still doesn't find the product by serial number.

**Comment by pedrobaeza** [comment]
`stock_barcodes_gs1` is not yet migrated, that fills the gap.
