### ISSUE TITLE
Generate barcodes for existing products

### ISSUE THREAD

**Issue by rubencabrera** [OCA/stock-logistics-barcode#30]
Barcode generator behaviour is good enough for new products, but some companies already work with odoo and have a large database of products, which would largely benefit from barcode implementation on their warehouse. 

We are working on this to do a PR to generate barcodes from existing product reference (default_code), but I open this issue to ask for feedback on any issue or request that might suit community interests.

**Comment by lasley** [comment]
You could just create a server action that searches for products without a barcode, then calls `generate_barcode()` on them. Seems this is a simple enough solution for something one-time like this IMO

**Comment by rubencabrera** [comment]
Thanks, @lasley, still have to try that, but seems a good solution!

**Comment by lasley** [comment]
@rubencabrera - An example can be seen [here](https://github.com/OCA/stock-logistics-barcode/pull/77/commits/e7fb1cf639cb488594980d77b723643630e143ed#diff-eed96e6c42bbce19bf81c29af81a8ec0R37)

**Comment by lasley** [comment]
@rubencabrera I'm going to close this issue. Ping me in the PR if you decide to make a glue module or something allowing for this functionality & I will review.

**Comment by rubencabrera** [comment]
That's fine, @lasley , I'll have it on hold for a while since there are some other priorities on that same project. Thanks for your attention.
