### ISSUE TITLE
12.0 > Product barcode generator > Unable to generate barcode

### ISSUE THREAD

**Issue by gregory-moka** [OCA/stock-logistics-barcode#302]
I tried to use this addon before install it on my databse, but, on runbot, I'm not able to generate barcode, or I'm missing something.  

I carefully read the documentation (on barecodes_genreator_product and barcodes_generator_abstract pages), and, even if the generator rules seems to be well set, I can't see the "Generate barcode" button on the product page, and the barcode is not generated automatically.   
![image](https://user-images.githubusercontent.com/45974412/96717534-e86eb380-13a6-11eb-9454-c4eb7c29aff8.png)

Does something has change around that on 12.0CE since 15 month ?  

Thanks for help

**Comment by gregory-moka** [comment]
@legalsylvain ?

**Comment by eguane** [comment]
Hi you need to modify user right like this
![image](https://user-images.githubusercontent.com/35990301/100328680-11e5b500-2fcd-11eb-9741-d01182eb0b70.png)
