### ISSUE TITLE
[13.0] It does not read the barcode, when it has been switched to manual entry

### ISSUE THREAD

**Issue by manuelcalerosolis** [OCA/stock-logistics-barcode#304]
In version 13 when you have switched to "manual input" it no longer executes the python function 'on_barcode_scanned', it seems that the manual entry button does not release the focus, as it did in version 12.0.

If I click on the bottom of the screen, it reads the barcodes.

Steps to reproduce the error:
1. Go to Inventory > operations > Inventory Adjustments.
2. Create new inventory with "Select products manually" option.
3. Start inventory.
4. Click to "Scan barcodes" smart button.
5. Change "Manual Entry" to 'On' and later to 'Off'
6. The barcode is not read.

Regards

@sergio-teruel 

![Peek 29-10-2020 11-23](https://user-images.githubusercontent.com/3088246/97556178-618a8e00-19d9-11eb-9ff3-4c06163c40a4.gif)

**Comment by albariera** [comment]
We have the same problem. Any news on this topic?

**Comment by albariera** [comment]
@sergio-teruel  Do you  know how to solve it? I have tried to search on your PR #348, but I have not been able to find it... It could be great to have a temporary solution until #348 is merged
Thank you! :blush:

**Comment by albariera** [comment]
@etobella

**Comment by sergio-teruel** [comment]
@albariera @manuelcalerosolis Can you try fixing like this:
https://github.com/OCA/stock-logistics-barcode/pull/348/files#diff-9d1148b192b848133c09e4649afb276603fc26458944f313ee2b26b1c02be921L27
