### ISSUE TITLE
"Scan Barcode" smart button missing from transfers

### ISSUE THREAD

**Issue by Avendere** [OCA/stock-logistics-barcode#324]
Usage instructions state,

"To use the barcode interface on a picking:

Go to Inventory > Transfers.
Click to “Scan barcodes” smart button.
Start reading barcodes."

Yet, I have no Scan barcodes button on the transfers page. I have the barcode buttons in operations overview but nothing in Transfers.

**Comment by Avendere** [comment]
I should add using Odoo 13. Behavior is the same on desktop and mobile. Windows and Android. No other addon modules installed.

**Comment by pedrobaeza** [comment]
Do you mean entering one specific picking, or in the list?

**Comment by Avendere** [comment]
Hi Pedro. 

My understanding is that in Overview where I can see barcode images are for scanning existing operations. Such as an expected receipt from purchasing or an existing sales order from Sales. If I scan a product in there then it is trying to match it against a product on an existing transfer right?

But if I want to do an Immediate transfer with no existing document then I go in Inventory > Transfers where I should see a Barcode scanning "smart button". But there is nothing. Not in the root page of transfers or if I create a transfer nothing inside. 

I do not know where it should be because I cannot find any images as guidance.

**Comment by pedrobaeza** [comment]
No, that doesn't exist yet. You have to always start from existing picking. I see that the README is slightly confusing in that part, as it's missing a point "Access to an existing picking".

**Comment by Avendere** [comment]
Oh ok. It is also confusing because it says right in the usage instructions that it is available :)

To use the barcode interface on a picking:

Go to Inventory > Transfers.
Click to "Scan barcodes" smart button.
Start reading barcodes.

**Comment by Avendere** [comment]
I see now, this is trying to demonstrate two different ways to get to the same existing picking. It is a little confusing. Thanks anyway.

**Comment by pedrobaeza** [comment]
Yeah, that's why I said that a point is missing. This should be the proper USAGE part:

- Go to Inventory > Transfers.
- Access to an existing pending picking.
- Click to "Scan barcodes" smart button.
- Start reading barcodes.

And it would be good to put your petition in roadmap part.

**Comment by Avendere** [comment]
ok I will add it. Thanks for your swift (and out of hours) response.

**Comment by Avendere** [comment]
Sorry, one last thing. Roadmap is pull requests yes?
