### ISSUE TITLE
product_barcode_generator: ean_sequence_id in product.product

### ISSUE THREAD

**Issue by yelizariev** [OCA/stock-logistics-barcode#33]
Probably, we don't need that field.

Check discussion: https://github.com/OCA/stock-logistics-barcode/pull/32#discussion-diff-71078250

**Comment by pedrobaeza** [comment]
Looking deeper, I see this as a way to fill the gap when a company has more than one GTIN prefix, and you want to use another prefix. I would prefer a way to define all prefixes at company level, and let the system decide which one is the next to use, but this one can be another way.

**Comment by lasley** [comment]
Shall we close this due to the new nomenclature based module? Company isolation is maintained there & I have customers using multiple GTIN prefixes in one installation without issues 👍
