### ISSUE TITLE
Generate Barcode (Abstract) v12

### ISSUE THREAD

**Issue by dani-xtendoo** [OCA/stock-logistics-barcode#336]
Good Morning,
We have a problem with the module "Generate Barcode (Abstract)" v12.
When we try to install it, odoo returns an error:
"Unable to install module "barcodes_generator_abstract" because there is an unresolved external dependency: invalid syntax".
The external library "python-barcode" was installed in our container without any problems.
How can we install the modulo "Generate barcode (Abstract) without any error?.
Thank you for your time.

**Comment by legalsylvain** [comment]
Hi @dani-xtendoo. Do you have installed the pinned version ? 
https://github.com/OCA/stock-logistics-barcode/blob/12.0/requirements.txt#L1

**Comment by dani-xtendoo** [comment]
Thank You for the answer @legalsylvain,
we have installed python-barcode but not the 0.12.0 version.
When we have added the version 0.12.0  for python-barcode, the modulo was installed witout problems.

**Comment by legalsylvain** [comment]
Thanks ! 

could you take a time to make a PR to update the installation part of the readme file ? 
https://github.com/OCA/stock-logistics-barcode/blob/13.0/barcodes_generator_abstract/readme/INSTALL.rst

**Comment by llacroix** [comment]
@legalsylvain any idea what's wrong with newer version of python-barcode? 

We can see here that it does indeed pass tests on python3.6
https://github.com/WhyNotHugo/python-barcode/actions/runs/1051859829

**Comment by legalsylvain** [comment]
No idea.

**Comment by bodedra** [comment]
Are we good to close this issue?

**Comment by legalsylvain** [comment]
@bodedra. Just waiting for @dani-xtendoo to improve the readme. 

kind regards.

**Comment by llacroix** [comment]
If there are no issues then the python-barcode version freeze should be removed from the requirements.txt it may cause version conflicts with other libraries.

**Comment by legalsylvain** [comment]
@llacroix : I dont understand, as there is issues with recent version.

**Comment by llacroix** [comment]
@legalsylvain how come branch 13.0 and 14.0 aren't version frozen then? What issues exactly? 

And I just tested version python-barcode-0.13.1 on odoo 12 with python3.6 without issues.

**Comment by legalsylvain** [comment]
Ok. I dont get it ! Let's go unpin latest version if all is ok.
