### ISSUE TITLE
Blueprint: GTIN Barcode Support

### ISSUE THREAD

**Issue by lasley** [OCA/stock-logistics-barcode#35]
GTIN is a barcode nomenclature that provides package, unit, and item references in the code + a mod10 checksum similar to EAN.

There are multiple types of GTIN - my project goal is specifically to GTIN14, but I believe I will be able to nail support for all of them because the lower ones are just zero padded. The other GTIN versions are encoded with EAN13 (GTIN13), UPC-A (GTIN12), or EAN8 (GTIN8)

Following are the high level items that need to be accomplished as part of this. It looks like we do have some logic available in [base_gs1_barcode](https://github.com/OCA/stock-logistics-barcode/tree/9.0/base_gs1_barcode) for the encoding too (GTIN14 is encoded as GS1-128).
- [ ] Base GTIN14 validation - #36 
  - Also known as EAN14. Can use similar logic to the existing EAN sums - too bad they're not more abstracted so I could just use them though 😦 
- [ ] GTIN\* => GTIN14 conversions
- [ ] Add a package reference column on `product.packaging` - this will need to be used to identify the quantity multiplier
- [ ] Add company prefix model, with `GS1`, `GS1-8`, and `UPC` as types. M2M with vendors, allowing for relation to their company prefix codes
- [ ] GTIN14 nomenclature type
  - First digit is indicator (how many quantity of package units)
  - Twelve digits following are GS1 company prefix and item reference
  - Last digit is check digit
- [ ] GTIN12 nomenclature
  - Eleven digit UPC Company Prefix
  - Last digit is check digit
- [ ] GTIN8 nomenclature type
  - Seven digit GS1-8 company prefix
  - Last digit is check digit

More info on GTIN:
- http://www.entmerch.org/programsinitiatives/packaging-labeling-and-edi/gtin-implementation-guide.pdf
- https://www.gs1us.org/Portals/0/gs1%20us%20library/standards/gs1%20identification%20numbers/An%20Introduction%20to%20the%20Global%20Trade%20Item%20Number%20(GTIN).pdf

Please let me know if this overlaps with anything existing, or if there are already existing strategies in existence for handling of GTIN 😄 

cc @t3ddftw

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/product-attribute/tree/8.0/product_gtin

A logical move is to bring this module here in 9.0 and remove it from the other repository.

**Comment by lasley** [comment]
PR #36
