### ISSUE TITLE
[14.0] barcode rules are not deleted

### ISSUE THREAD

**Issue by Mat-moran** [OCA/stock-logistics-barcode#377]
## Module
barcodes_generator_abstract

## Describe the bug
It seems that barcode rules are not deleted when yo delete from the barcode nomenclature table neither when you delete the barcode nomenclature.

## To Reproduce

1. Go to Settings / Technical / Sequences & Identifiers / Barcode Nomenclatures
2. Create a Nomenclature
3. Create a rule with EAN13 codification
4. Select Generate type --> `Base set manually`
5. Generate model --> `Products`
5. Click on `Automatic Generation`
6. Save
7. Delete
8. Repite the process and you get `Validation Error: Only one rule per model can be used for automatic barcode generation.`

This happen because the rule itself has not been deleted and even yo can select it from the product template  after delete it.

**Expected behavior**
The rule should be deleted when you delete from Nomenclature table.

**Additional context**
Odoo version 14.0

**Comment by legalsylvain** [comment]
This bug is about odoo not oca module. Could you open an issue on odoo/odoo if it occures in V16 ?
Thanks !
