### ISSUE TITLE
(14)After successful installation, the driver cannot be

### ISSUE THREAD

**Issue by TTT1996** [OCA/stock-logistics-barcode#379]
## Module
stock_barcodes

## Describe the bug
After successful installation, the code scanner will not work。
in 13，use the code scanner，have‘post /web/dataset/call_kw/wiz.stock.baicodes.read.picking/onchange....."
but in 14, use the code scanner,have not

**Comment by pedrobaeza** [comment]
Unless you give more hints about the problem, nothing can be done. Anyways, the barcode detection part is not from this module, but Odoo core one.

**Comment by yehebihr** [comment]
Check here 


https://github.com/OCA/stock-logistics-barcode/issues/420#issuecomment-1235854091
