### ISSUE TITLE
How to install Product_barcode_generator? Barcode Generator Error

### ISSUE THREAD

**Issue by helpdesknl** [OCA/stock-logistics-barcode#39]
Greetings Odoo enthusiasts... 

I'm pretty new to Odoo but i like the system very well so far. I only have one problem when trying to install apps/modules from third party's to Odoo, every time i do this the installation gives a trace back call error, odoo server error or openerp error. With some apps it won't give an error but it won't install.

The apps i tried to install are: 

Product_barcode_generator from https://github.com/OCA/stock-logistics-barcode
Product_barcode_generator_custom from https://github.com/it-projects-llc/pos-addons#9.0
Mass label reporting from https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/tree/9.0

My installation is V9.0 community edition and i'm running it on Ubuntu server 16.04 LTS. 

I hope someone can help me with this issue. Greetings and allready thanks for the help

**Comment by lasley** [comment]
Hi @helpdesknl - I can confirm that Product_barcode_generator from OCA works in 9.0 runbot. Please submit in the repo containing the failing module, which can be determined by installing one at a time.

**Comment by lasley** [comment]
Although do note that the 9.0 module is called `barcodes_generator_product`
