### ISSUE TITLE
[14.0] barcode rules are not passed to `product.product`

### ISSUE THREAD

**Issue by Mat-moran** [OCA/stock-logistics-barcode#400]
## Module
barcodes_generator_product

## Describe the bug
There are different problems related with this module.

### **barcode rules** are not passed to `product.product`
- When you create a new product and the `automatic_generation=False` you can not create the product if you assign a barcode rule, and you can not assign a barcode rule once the product has been created for the same reason. This probably is because the `generate_type` is only apply to the first variant as you can see in the image.

![image](https://user-images.githubusercontent.com/4810013/159462361-974001b2-f85b-4b39-8611-3d1353e1a787.png)
![image](https://user-images.githubusercontent.com/4810013/159463718-e8e84dba-b3fc-4ab5-9c4e-e406967acf66.png)

## To Reproduce
**Affected versions**:

1. Create a barcode nomenclature
2. Create a new rule for EAN13 barcode with no automatic generation
3. Create a product with variants
4. You should get the above error

**Expected behavior**
Products variants should get the correct `generate_type` from the rule you are defining in the `product_template`

**Additional context**
- Odoo version: 14.0

**Comment by legalsylvain** [comment]
Hi @Mat-moran.

>  Products variants should get the correct generate_type from the rule you are defining in the product_template

This module doesn't define ``generate_type`` on ``product.template`` but on ``product.product`` level.

Defining ``generate_type`` on the second ``product.product`` should fix the bug. Or did I missed something ?

regards.

**Comment by Mat-moran** [comment]
Thanks for the answer @legalsylvain,

Yes if you assign the `barcode_rule` manually to the variants this solve the problem **partially** with the drawback that to do it manually with a `server_action`. I say partially because if you  create a new variant after barcodes has been generated, it does not work properly the sequence is lost. 

All the problems are solve with the `automatic_generation=True` but the problem with this is that its applied to all products as I explain in #401 .

**Comment by cramosh** [comment]
Hi @legalsylvain this field is define in the model product.template from module barcodes_generator_product. Is a selection field related with product_variant_ids
![captura](https://user-images.githubusercontent.com/34350771/159467885-3a0b1fc6-a451-45ec-a19c-af6a5512bc74.png)

**Comment by legalsylvain** [comment]
yes, so it should be but on the product.product level. 
the product.template level only works on a mono-variant context.

Well, in fact it is exactly design as ``barcode`` field.
if you create have a variant 1 with value A in ``barcode`` field and if you create an variant B, the ``barcode`` field will be empty. The same occures for this module.

**Comment by Mat-moran** [comment]
Here is an image with a barcode generated with variants already created applying the barcode rule with a server action.

![image](https://user-images.githubusercontent.com/4810013/159468603-c544b855-dc1e-4a30-ae81-ac2009868117.png)

When I create a new variant, apply again the barcode rule of the product template and try to generate the new barcode I get the next error saying that one barcode only can by apply to one product. We are going to investigate further this problems.
![image](https://user-images.githubusercontent.com/4810013/159469018-e0a6ab5e-b5ae-4545-aca0-db9223b1397e.png)

**Comment by cramosh** [comment]
> 

This example is ok. But when i create a template and assing one category, this category is same from all variants

**Comment by cramosh** [comment]
> > 
> 
> This example is ok. But when i create a template and assing one category, this category is same from all variants

**Comment by Mat-moran** [comment]
@legalsylvain I see you are checking #401 , probably this one is more important and solves partially this issue because with automatic generation the workflow id OK. Thanks for the quickly answer.
