### ISSUE TITLE
[14.0] barcode is generated when no barcode rule is selected if a barcode rule has `automatic_generation=True` 

### ISSUE THREAD

**Issue by Mat-moran** [OCA/stock-logistics-barcode#401]
## Module
barcodes_generation_product

### automatic generation of barcodes IMO should be bounded to the rule itself
Now when you defined a rule with automatic generation it applies to all the products, even if you do not select this rule during the creation of the product. IMO the automatic barcode generation should only happen if you select an automatic rule in the product.

## To Reproduce
**14.0**:

1. Create a barcode nomenclature
2. Create a new rule for EAN13 barcode with automatic generation
3. Create a new product without selecting the automatic generation rule
4. You should get the new product with a barcode generated.

**Expected behavior**
The automatic generation of the barcode IMO should be bounded the the context of the rule. Only generate an automatic barcode if you select one of the automatic rules you can have in the system.

**Additional context**

**Comment by legalsylvain** [comment]
@lasley : could you take a look on this one, as you implemented the automatic mechanism.

thanks !

**Comment by Mat-moran** [comment]
Hi @lasley sorry for ping you but this matter is urgent for us, are you going to check this? If you can not do that we can give a try and do a PR.

**Comment by rafaelbn** [comment]
@lasley doesn't' work in Odoo anymore at least 3 years ago.

**Comment by Mat-moran** [comment]
Thanks @rafaelbn,
@rafaelbn, @legalsylvain  are you OK if we propose a PR in this direction??

**Comment by legalsylvain** [comment]
>  @rafaelbn, @legalsylvain are you OK if we propose a PR in this direction??

hi @Mat-moran

Indeed ! Please add tests for the automatic generation workflow.

**Comment by rafaelbn** [comment]
My opinion is I'm agree with this direction. I'm not PSC of this repo.

My suggestion is that more @OCA/logistics-maintainers-psc-representative could give their vision.
