### ISSUE TITLE
[14.0]: after installing all needed gs1 modules, system still can't pares GS1 data matrix 2D code ! 

### ISSUE THREAD

**Issue by yehebihr** [OCA/stock-logistics-barcode#406]
After installing ( Stock Barcodes ,GS1 Barcode API , Stock Barcodes GS1, and Stock Barcodes GS1 Expiry)  system still not able to parse GS1 data matrix 2D codes 

So when I receive a product by scanning the  GS1 data matrix 2D code,  the following should happen:

1- items shows up by recognizing its GTIN 
2- lot number get updated 
3- SN added
4- Expiry date added 

But, what is happing now is showing  incorrect barcode warning message showing the whole GS1 code

Do I have to add GS1 nomenclatures  to the barcode nomenclatures in order to work ? 

Also why [GS1-128/GS1-Datamatrix barcodes] appears in User Right form ? can you explain how to use it ?
<img width="1245" alt="Screen Shot 2022-04-19 at 7 38 03 AM" src="https://user-images.githubusercontent.com/16811333/163922264-09fec6f0-a4f7-4dde-9c47-27c6b9d61112.png">

@StefanRijnhart 
@sergio-teruel

**Comment by yehebihr** [comment]
Anybody can help please 🥲

**Comment by yehebihr** [comment]
Help is needed!

**Comment by yehebihr** [comment]
Hello!! Can anybody help 🥲 please?

**Comment by rousseldenis** [comment]
@yehebihr Could you please :

- Enumerate the modules you've installed.
- The exact flow that is problematic ('So when I receive a product by scanning...' - What do you do exactly? - Which screen?...)
- The error message you have (if you have one).
- Maybe a way to reproduce on runboat

**Comment by yehebihr** [comment]
Hey @rousseldenis   

As requested

- Enumerate the modules you've installed:

  - stock_barcodes
  - stock_barcodes_gs1
  - stock_barcodes_gs1_expiry
  - base_gs1_barcode (GS1 Barcode API)

- The exact flow that is problematic:

  After installing the mentioned modules above, system still can't parse gs1 2D data-matrix code.
  when using barcode interface on a  receiving or picking and start scanning  gs1 2D data-matrix code, the system generate error.

- The error message you have (if you have one).
  Barcode: 010622107515007821188439251117220727106719015 (Barcode not found)

Can you please  provide an explanation on how to configure and use these modules?

**Comment by sergio-teruel** [comment]
Hi @yehebihr maybe there is any commit that has not applied un v14.
I Will rewiew this...

**Comment by sergio-teruel** [comment]
Fixed here https://github.com/OCA/stock-logistics-barcode/pull/429

@yehebihr Can you test?

**Comment by yehebihr** [comment]
@sergio-teruel thanks for your fast response!

I tested the module after installing the new updates but still cannot parse the gs1 barcode

Check the below screen shot for the error 

![image](https://user-images.githubusercontent.com/16811333/187659386-8d1b3e7f-4178-4c8d-ad69-96e2541aaa21.jpeg)

**Comment by sergio-teruel** [comment]
Ok!! I will review more deeply.
Can you copy and paste the full GS1 number and I'll check

**Comment by sergio-teruel** [comment]
With the lastest changes, now you must select in every operation type the proper scann option.

Can you check this??

**Comment by yehebihr** [comment]
010622107515007821188439251117220727106719015

https://barcode.tec-it.com/barcode.ashx?data=010622107515007821188439251117220727106719015&code=GS1DataMatrix&translate-esc=true&dmsize=Default

**Comment by yehebihr** [comment]
> With the lastest changes, now you must select in every operation type the proper scann option.
> 
> 
> 
> Can you check this??

Let me check and get back to you

**Comment by yehebihr** [comment]
> With the lastest changes, now you must select in every operation type the proper scann option.
> 
> Can you check this??

@sergio-teruel  As requested,  I selected the proper scan option for every operation type.

For example 

-  Receipts -> picking in option 
- Delievry Orders -> picking out option

But, still the system can't parse the gs1 barcode as shown in the picture  below.
<img width="800" alt="Screen Shot 2022-08-31 at 5 24 43 PM" src="https://user-images.githubusercontent.com/16811333/187707284-b243b24e-59b4-4a54-ac50-eccc4d6ec4a3.png">

**Now To be in the picture, let me explain my needs:**

My process is as follow:

1-  I create a PO and send it to vendor 
2- Confirm PO once order is confirmed by vendor 
3- When order is delivered I go to receipt and start receiving the order using barcode interface
4- the products I'm receiving have  gs1 datamatrix barcodes that have info  such as GTIN numbers, expiry dates, lot numbers, serial numbers. Im assuming All those info are supposed to be mapped out to the proper fields in the product templates.

5- When selling the products I will be using   gs1 datamatrix barcodes in POS to in order to track each product using either SN or LOT NUMBER 


lastly, Do you guys have a user manual to learn how to configure these modules. I tried to follow all the provided instructions  but I still couldn't figure out how to configure some modules


Thanks for your help, it is highly appreciated

**Comment by sergio-teruel** [comment]
Thanks for your explanation.

I will review it

We have to change the help documentation....

**Comment by sergio-teruel** [comment]
Hi.. 

An error occurs when the module base_gs1_barcode try to decode the barcode

https://github.com/OCA/stock-logistics-barcode/blob/14.0/base_gs1_barcode/models/gs1_barcode.py#L202

The position error is 38. At this moment I don't have a 2d reader so I can't check it

**Comment by yehebihr** [comment]
Kindly, would you please elaborate more on in more details about the errors ?


Thanks

**Comment by yehebihr** [comment]
Dears,

Kindly, please any updates on the issue.


Thanks,

**Comment by yehebihr** [comment]
> Hi.. 
> 
> 
> 
> An error occurs when the module base_gs1_barcode try to decode the barcode
> 
> 
> 
> https://github.com/OCA/stock-logistics-barcode/blob/14.0/base_gs1_barcode/models/gs1_barcode.py#L202
> 
> 
> 
> The position error is 38. At this moment I don't have a 2d reader so I can't check it
> 
> 
> 
> 

@sergio-teruel 

Any update regarding the issue please ?!

Also, I have a question regarding the POS operation, what scanning option should we assign? Do we use "pick out" ?

**Comment by yehebihr** [comment]
> Hi.. 
> 
> 
> 
> An error occurs when the module base_gs1_barcode try to decode the barcode
> 
> 
> 
> https://github.com/OCA/stock-logistics-barcode/blob/14.0/base_gs1_barcode/models/gs1_barcode.py#L202
> 
> 
> 
> The position error is 38. At this moment I don't have a 2d reader so I can't check it
> 
> 
> 
> 

@rousseldenis 
@sergio-teruel 

Could you please help ?

**Comment by sergio-teruel** [comment]
Sorry @yehebihr I had some tests with a Zebra MC93 and I think that your code is not good..
Have you any picture (Not generated by you) of a barcode datamatrix 2d?

**Comment by yehebihr** [comment]
@sergio-teruel 

Thanks for getting back to me 

Please see the attached file for Gs1 datamatrix codes 

![image](https://user-images.githubusercontent.com/16811333/189983626-3968a237-5914-4a0a-ba11-b85fcd9ac7f8.jpeg)

Your support is greatly appreciated 

Thanks

**Comment by yehebihr** [comment]
> Sorry @yehebihr I had some tests with a Zebra MC93 and I think that your code is not good..
> 
> Have you any picture (Not generated by you) of a barcode datamatrix 2d?
> 
>  

@sergio-teruel thanks for getting back to me 

I've attached a few examples of the gs1 data matrix barcode below:

![image](https://user-images.githubusercontent.com/16811333/190020451-020a5d9a-d3f4-4fd0-ac54-39c0a4f56e47.jpeg)

![image](https://user-images.githubusercontent.com/16811333/190020158-dc92199c-d61d-40a1-ba4f-c29e7f0c051a.jpeg)

Your support is greatly appreciated 

Thanks,

**Comment by yehebihr** [comment]
@sergio-teruel 

Soft reminder

**Comment by yehebihr** [comment]
@rousseldenis 
@sergio-teruel 

Is there any update on this please?

**Comment by yehebihr** [comment]
@LoisRForgeFlow Can you please help?

**Comment by yehebihr** [comment]
@sergio-teruel 
@rousseldenis 
@rvalyi 

Still can't make it works!

Any help please?
