### ISSUE TITLE
[14] stock_barcodes not reading barcods

### ISSUE THREAD

**Issue by codegrove-dev** [OCA/stock-logistics-barcode#420]
## Module
stock_barcodes

## Describe the bug
After installing the stock_barcodes module, we can see the "scan barcodes" button in any picking, and it will open up the wizard. Inside the wizard there is nothing happening when reading a barcode, neither in the main screen nor inside a manually chosen picking. Also, the manual entry data does not react to a scanned barcode.
The barcode reader itself works (scanning barcodes to any text field gives correct results)

## To Reproduce
**Affected versions**: 14

1. Install module
2. Go to any Sale Order > Delivery > Scan Barcodes
3. Scan a barcode

**Expected behavior**
The scanned product should be added to the picking, some kind of message should appear.

**Additional context**
Odoo 14 open source, self hosted

**Comment by yehebihr** [comment]
With the lastest changes, now you must select in every operation type the proper scann option.

For example,

Receipts -> pick in
 Delivery Orders -> pick out

To do this:

1- Go to inventory 
2- go to configuration
3- operation type
4- scroll down to barcodes and select the proper scan options 

https://github.com/OCA/stock-logistics-barcode/issues/406#issuecomment-1232770687
