### ISSUE TITLE
[14.0][stock_barcodes] Wizard window don't update amount done while you are scanning

### ISSUE THREAD

**Issue by Bilbonet** [OCA/stock-logistics-barcode#462]
In this case the need is to pick out the products from a sale order. The operative is scan the code bar product and if it's correct picks it up.

As you can see in the image.
Wizard window don't update amount done while you are scanning. I have to server 4 units and I've already scanned two but windows still to 0.
If I click in the line opens de window with the correct information.

![imagen](https://user-images.githubusercontent.com/8178160/201962192-592f930d-01f8-4a70-a7f6-49641ea53d67.png)

Even it would be good that the line change the color if the amount demanded is different that amount done.

**Comment by alessiom72** [comment]
I can confirm the bug. It seems the method _compute_qty_done() of the class WizStockBarcodesReadTodo is not triggered by the change in line_ids.qty_done.

**Comment by Bilbonet** [comment]
Yes, the method is not triggered. I don't know why. 
Maybe because the relation with the field "line_ids" is many2many.


== The Fields ==
https://github.com/OCA/stock-logistics-barcode/blob/17421ab14d85eda761523da2c1d01210d43e1913/stock_barcodes/wizard/stock_barcodes_read_todo.py#L41-L47

https://github.com/OCA/stock-logistics-barcode/blob/17421ab14d85eda761523da2c1d01210d43e1913/stock_barcodes/wizard/stock_barcodes_read_todo.py#L63

== The Method ==
https://github.com/OCA/stock-logistics-barcode/blob/17421ab14d85eda761523da2c1d01210d43e1913/stock_barcodes/wizard/stock_barcodes_read_todo.py#L192-L195

Any suggestion to solve this?
@alessiom72 @sergio-teruel

**Comment by pedrobaeza** [comment]
Closing as existing PR. It's very uncomfortable to have to open 2 things to analyze the thing.
