### ISSUE TITLE
[14.0][stock_barcodes] method action_force_done() is triggered reading barcodes

### ISSUE THREAD

**Issue by Bilbonet** [OCA/stock-logistics-barcode#463]
When you read a product barcode that is not in the picking. 

1. The wizard shows  the wrong product found.
2. The button with the action action_force_done() is visible.

Then, if you read another barcode the button with the action is triggered. And create a new stock move.

![stock_barkodes](https://user-images.githubusercontent.com/8178160/201987867-daf0fc34-5d86-471e-94f3-d58cbf442417.gif)

**Comment by rousseldenis** [comment]
@sergio-teruel @LoisRForgeFlow @pedrobaeza @chienandalu

**Comment by pedrobaeza** [comment]
Closing as there's an existing PR. Next time, if you plan to do a PR, you can explain the issue in the PR itself instead of opening 2 things.

**Comment by sergio-teruel** [comment]
@Bilbonet CAn you try this on v15?

**Comment by Bilbonet** [comment]
@sergio-teruel @pedrobaeza @rousseldenis 
I've tried on v14 and v15 and now works fine.
I was wrong
