### ISSUE TITLE
[14.0]stock_barcodes: Picking out operation bug

### ISSUE THREAD

**Issue by davidepiu14** [OCA/stock-logistics-barcode#468]
# stock_barcodes

## Description
Creating a new stock.operation operation from the button "New" it's nearly impossible to read the product with the barcode scanner. Randomly the product barcode is recognized and in the logs I see this error:

`UPDATE "wiz_stock_barcodes_read_picking" SET "write_uid"=2,"write_date"=(now() at time zone 'UTC') WHERE id IN (130)
ERROR: could not serialize access due to concurrent update`

## To Reproduce
**14.0**:

1. Create a new picking OUT stock.operation clicking on the button "New" ("Nuovo")
 ![image](https://user-images.githubusercontent.com/61499360/204516588-529a2a2f-ded3-42bb-a504-16392c964f66.png)
2. Scan the product barcode once inside the wizard
3. Nothing happens, if you continue to scanner (after like 40/50 scans the product is recognized)
![image](https://user-images.githubusercontent.com/61499360/204518051-3dbc957e-7ed4-4e15-9234-2bee080ba37d.png)
4. This error appears in logs: 
``bad query: UPDATE "wiz_stock_barcodes_read_picking" SET "write_uid"=2,"write_date"=(now() at time zone 'UTC') WHERE id IN (130) ERROR: could not serialize access due to concurrent update``

In the "picking out option" I had selected the product barcode scan as a first move.
![image](https://user-images.githubusercontent.com/61499360/204517613-01e434f5-0749-4ebc-aaef-c71496c6a8f5.png)

**Expected behavior**
1. Create a new picking OUT operation clicking on the button "New"
2. Start scanner products
5. Product is added to the stock.operation

**Comment by chrisdilbert** [comment]
Same problem on version 15.0

**Comment by chrisdilbert** [comment]
odoo.sql_db: bad query: UPDATE "wiz_stock_barcodes_read_picking" SET "write_date"='2023-03-10 02:32:51.973158',"write_uid"=2 WHERE id IN (74)
ERROR: could not serialize access due to concurrent update
