### ISSUE TITLE
[15.0]stock_barcodes defect for Exception - AttributeError: 'stock.picking' has no attribute 'put.in.pack'

### ISSUE THREAD

**Issue by nicolas-tg** [OCA/stock-logistics-barcode#492]
## Module
The name of the module that has a bug: stock_barcodes: https://github.com/OCA/stock-logistics-barcode/tree/14.0/stock_barcodes

## Describe the bug
Defect error message when we validate the Receipt Transfer after setting Done quantities from Barcode Scanner.

## To Reproduce
**Affected versions**: 15.0, and probably earlier versions.

1. Configure the Barcode Options with "Auto Put In Pack" [auto_put_in_pack] = true for Picking IN and set it for your Operation Type Receipt.
2. Scan your Receipt using barcode scanner, to set done quantities for products
3. Click "Validate" on the Receipt it will show the defect.

**Expected behavior**
If this configuration is enable from the Barcode Options, but we do not use Packs or Lots, the Users should see an error message.

**Additional context**
![stock](https://user-images.githubusercontent.com/99798707/218057782-19004ab1-66d8-48c5-8ddd-363dda8ee07b.png)

Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by rousseldenis** [comment]
@pedrobaeza 

Maybe related to this ? https://github.com/OCA/stock-logistics-barcode/pull/454/

**Comment by pedrobaeza** [comment]
Maybe... I assign my colleague which is the father of the creature.

**Comment by nicolas-tg** [comment]
I edited the issue request.

**Comment by rousseldenis** [comment]
> I edited the issue request.

@nicolas-tg Thanks, indeed, the PR pointed is solving that problem (for v14).

**Comment by nicolas-tg** [comment]
Thanks! Let me know if you want me to QC anything. If possible, I would like this issue to be sorted in v15.

**Comment by sergio-teruel** [comment]
@nicolas-tg Fixed here https://github.com/OCA/stock-logistics-barcode/pull/493
