### ISSUE TITLE
[14.0] stock_barcodes: regression on inventory

### ISSUE THREAD

**Issue by alexis-via** [OCA/stock-logistics-barcode#565]
The PR https://github.com/OCA/stock-logistics-barcode/pull/560 by @dalonsod  has introduced a regression: it uses the fields "user_id", "inventory_quantity_set" and "inventory_date" and  on stock.quant, which exists on odoo v15 but NOT on odoo v14 !

There is the code which uses the non-existing user_id + inventory_quantity_set + fields inventory_date on stock.quant: https://github.com/OCA/stock-logistics-barcode/blob/14.0/stock_barcodes/wizard/stock_barcodes_read_inventory.py#L28

**Comment by alexis-via** [comment]
```
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/14/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/14/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field stock.quant.inventory_date in leaf ('inventory_date', '<=', datetime.date(2023, 12, 14))
```

**Comment by dalonsod** [comment]
Ouch. It's clear we missed reviewing that option, and tests were passed anyway.

We'll take a look and solve it ASAP.

cc @ChristianSantamaria @sergio-teruel

**Comment by alexis-via** [comment]
Any news ? Can I help on this regression ? I'm not very familiar with this code, but I'm ready to help !

**Comment by dalonsod** [comment]
We'll started with it, but not working yet 😞, so no PR is created yet. We'll continue with it...

**Comment by dalonsod** [comment]
@alexis-via #569
