### ISSUE TITLE
[16.0] Table 'product_barcode': unable to set NOT NULL on column 'barcode'

### ISSUE THREAD

**Issue by iberomed** [OCA/stock-logistics-barcode#568]
## Module
I don't reallly know but it seems to be product_multi_barcode

## Describe the bug
When I try to clone the production enviroment (my main branch) to another enviroment (staging, for example) I get this error:

**'product_barcode': unable to set NOT NULL on column 'barcode'**

Also there is this other error:

ValueError: Wrong @depends on '_compute_barcode' (compute method of field product.product.barcode). **Dependency field 'name' not found in model product.barcode.**

I have checked that table product_barcode doesn't have a field called 'barcode', so I think the error makes sense, but I don't know why is throwing this error.

## To Reproduce
**Affected versions**:

1. Clone main branch which have installed stock-logistics-barcode modules installed making another enviroment branch (ie staging)

**Expected behavior**
The expected behaviour is to get a staging or dev enviroment as the odoo normal behaviour before install the module.

**Additional context**
odoo.sh v16

**Comment by legalsylvain** [comment]
Hi @iberomed. 

Could you reproduce the bug out of odoo.SH ? (On the Oca runboat for exemple)

If this problem occures only on odoo.SH please contact odoo.SH support. 

Thanks !
