### ISSUE TITLE
Dev branch on OCA repo

### ISSUE THREAD

**Issue by lasley** [OCA/stock-logistics-barcode#59]
Hi @legalsylvain - Looks like we have one of your branches on OCA side. I ❤️  your naming schema btw, people trying to find me based on my branch names would be screwed 😆 

![image](https://cloud.githubusercontent.com/assets/7397578/21030010/203c5516-bd51-11e6-9d19-56dfb9e841f8.png)

**Comment by lasley** [comment]
I have deleted this branch due to no response

**Comment by legalsylvain** [comment]
@lasley sorry I did not see this issue. thanks for cleaning this OCA repo, and sorry for the annoyance.

**Comment by lasley** [comment]
No worries - I just hope I didn't delete anything that you didn't have on local!
