### ISSUE TITLE
[15.0][16.0] Bug report - Impossible to Open barcode Rule from product

### ISSUE THREAD

**Issue by PlantBasedStudio** [OCA/stock-logistics-barcode#591]
## Module
barcode_generator_product

## Description
We just can't open Barcode Rule in [15.0] and [16.0] versions
I opened à runboat on 16.0

![image](https://github.com/OCA/stock-logistics-barcode/assets/83568840/24fb995f-575b-4c77-9a02-ff487e43ac0c)

## To Reproduce
Just open a product and click on the arrow to open barcode rule

1. Go to products
2. Select one
3. Open barcode rule by clicking on the arrow

**Expected behavior**
Should open the barcode rule window

**Comment by legalsylvain** [comment]
hi @PlantBasedStudio. Thanks for reporting. tested on runboat and locally. Bug confirmed. However, I have no idea why this bug occures. As it makes no sense to create / edit a barcode rule from product. (barcode rule should be created / edited from barcode nomenclature, I propose to put a widget selection on that field).
