### ISSUE TITLE
Update form with UOM and Quantity

### ISSUE THREAD

**Issue by fohnbit** [OCA/stock-logistics-barcode#69]
Hi,

the app is great. Very helpful, but maybe you can add 2 functions?:
1. display the UOM ... when counting it is important to know the UOM
2. Jump with the cursor in the "add_qty" field .. so you can add the Quantity and just press Enter to Update

Thank you and happy new year

edit: I use odoo8

**Comment by lasley** [comment]
Hi @fohnbit - What specific module are you referring to?
