### ISSUE TITLE
[9.0] Need help. barcodes_generator_product issue, me or everyone?

### ISSUE THREAD

**Issue by odaybari** [OCA/stock-logistics-barcode#71]
Hi 
Please help,
I Have installed barcodes_generator_product and barcodes_generator_abstract in V 9.0. Followed the instruction and setup "auto generating" and manual once at a time for products. Barcode are not generated automatically either manually ( no buttons in product template).

pyBarcode installed.

Thanks

**Comment by odaybari** [comment]
Any help please?

**Comment by pedrobaeza** [comment]
Sorry, but this is not an issue (bug) itself. If you put any kind of log error, maybe there can be a bug, but if no more information, there's nothing to do.

Interesting link: http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by lasley** [comment]
Closing - please reopen after reading @pedrobaeza's link & with more info
