### ISSUE TITLE
[8.0][product_multi_ean] Question: When do I enter and prioritize additional EAN13 Codes

### ISSUE THREAD

**Issue by azeemism** [OCA/stock-logistics-barcode#78]
Hi. I installed this module but am confused where I can enter multiple EAN13 Codes and set their Priorities?

When I go to the product, I only see one EAN13 box:

![2017-02-08 13_32_54-products - erp](https://cloud.githubusercontent.com/assets/10731034/22759387/1da4c1d0-ee07-11e6-8818-c191c5fdaf38.png)

Thanks for all you do.

**Comment by lasley** [comment]
Hi @azeemism - The EAN is only visible on the Product Variant, you are looking at the Product Template. I have confirmed that this works by Going to Warehouse => Products => Apple In-Ear Headphones => Variants (tab) => 1 List of Variants (button) => [A8767] Apple In-Ear Headphones:

![image](https://cloud.githubusercontent.com/assets/7397578/23089786/08f05c2e-f544-11e6-9efa-3d8d0ad7725d.png)
