### ISSUE TITLE
[RFC] pos_stock_picking: POS for carrier drivers

### ISSUE THREAD

**Issue by lasley** [OCA/stock-logistics-barcode#79]
This module will extend v10 point of sale to provide a `stock.picking` delivery interface. The main goal is to provide offline access to a set of pickings for the day, aggregating all movements into a session - just like POS. 

I think we will be able to reuse a lot of the existing POS assets, then we can glue in the interface from [`web_stock_picking`](https://github.com/OCA/stock-logistics-barcode/pull/38). We will be rewriting `web_stock_picking` with this in mind in order to allow for the widget to be used in this context & searches to be localized.

I envision a delivery terminal working in the exact same way a POS terminal would in a lot of cases, except we'll be using `stock.picking` instead of `product.product` for the initial scan. I'm thinking it can even go in the same "Point of Sale" top level menu, although maybe it would make sense to make a new menu "Delivery" or something.

The option to use the delivery interface for a POS terminal will be enabled in `pos.config` using a new `is_delivery_terminal` attribute. If this attribute is enabled, a warehouse can optionally be selected to indicate where the terminal is based from to provide data filtering. If a session is initiated for a delivery terminal, the delivery interface will be shown instead of the POS interface.

Instead of the approach of preloading everything, we will assume that the delivery session starts in an online setting (the warehouse). The standard `stock.picking` workflow will take place, with the picking agent scanning a picking barcode & scanning lots/products to fill the picking. 

A new "Queue Delivery" option will be added to the picking interface. Using this option will add the `stock.picking` into a `pos.delivery` & cache the picking + related data (lot, etc). Restarting the POS session will recache the correct `pos.delivery`, which will allow for a reload or whatever.

A new view will be added into the picking interface to view high level info of queued deliveries. Picking barcodes may also be scanned to simply bring up the picking. A new field `delivered_qty` will be added to `stock.picking`, and scanning the products/lots associated with the current picking will add to those quantities - just like it would when you scan for pickings.

This module will also optionally gather a signature from the receiving party in order to confirm delivery. This signature will be stored with the `stock.picking` by using a `mail.thread` using [`jSignature` from web](https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/web/static/lib/jSignature/jSignatureCustom.js#L2) in a similar way as `website_quote`. The option will be set in the delivery terminal config.

Confirming the delivery will set the `pos.delivery` to done. 

When closing the session for a delivery terminal, the `pos.delivery` for the session will be displayed above the summary by payment methods. Summary by payment methods will be left for future plans of allowing CoDs via the existing `pos.order`. That's not coming in the first version though unfortunately.

Validating the entries will perform the changes on the associated `stock.picking`s (validate, add delivered qty, add signature). Undelivered items will need to be reconciled in a way similar to missing cash.

Sorry for the long RFC here, the requirements are quite dense. I can't find anything remotely like what I'm looking for, even in terms of delivery type workflows. I am also planning on splitting out some of the logic from [`delivery_internal`](https://github.com/OCA/stock-logistics-workflow/issues/304) to offload the requirements, but figured it was worth slight scope overlap in order to provide a complete picture.

Anyone have any thoughts?

**Comment by rafaelbn** [comment]
I think we could close this one.
