### ISSUE TITLE
How to enable barcode number auto-generation?

### ISSUE THREAD

**Issue by nkomate** [OCA/stock-logistics-barcode#90]
Firstly, I am new to Odoo and sorry for this silly question.

I've successfully installed the module onto my Odoo8 server.

Every time I create a product and its variants, I have to press "Generate the EAN13" button for each variant to generate the barcode number.

How do I set the module to have a barcode number generated automatically when a product is created?  I tried to look around all over the place but couldn't find where to set this.

Thank you in advance for any help.

**Comment by tonyjona** [comment]
@nkomate  I am very new to Odoo, and would you please to give me help on how to installed the module onto odoo. thanks!

**Comment by rousseldenis** [comment]
@nkomate Is this fixed ?
