### ISSUE TITLE
[Q][Resolved] How to activate the plugins?

### ISSUE THREAD

**Issue by IOAyman** [OCA/stock-logistics-barcode#91]
So I have just installed the plugins on a fresh Odoo instance which only has the Inventory app installed.
The problem is that, when I create a new product I'm not seeing the barcode generation  rule selector anywhere.

![screenshot_2017-04-19_15-44-37](https://cloud.githubusercontent.com/assets/6185849/25186219/d6364832-251f-11e7-9e52-fd05f6cd8f47.png)

A little guidance with that, please? I'd be grateful :)
 - - -
version `Odoo Server 10.0-20170419`

**Comment by himalsaman** [comment]
same problem please how active it in product form

**Comment by IOAyman** [comment]
I had to enable the user to be able to generate barcodes from Settings>Users.

I think this should be documented.

**Comment by diranetafen** [comment]
@IOAyman Thank you for this sharing this solution, you save me a lot of day of research !

**Comment by IOAyman** [comment]
@diranetafen, You're welcome! Glad to have helped 😄
